# Generated by Django 3.2.4 on 2021-06-29 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoardObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('path', 'Path')], max_length=16)),
                ('data', models.JSONField(default=dict)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_objects', to='whiteboard.board')),
            ],
        ),
    ]
