# Generated by Django 3.2.4 on 2021-08-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_board_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarduser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('shared', 'Shared')], default='owner', max_length=12),
            preserve_default=False,
        ),
    ]
